<a href="https://colab.research.google.com/github/prakash27/CSL522_ML/blob/master/assignments/assignment_1_name.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CSBB311: Machine Learning

**Instructor** : [Dr. Gautam Kumar]



# Practice question: Introduction to Python


**Student Name: Aashish Khaniya**

#Instructions


You must save your as Assignment_NO_Yourname

To complete assignment one, first you have to add your name and roll no in the Google Colab Instructions section below and print it. Perform the 10 task given in the assignment and submit it over Microsoft Team.

Your source file will most likely end in **.pynb** if you are using a Jupyter notebook; however, it might also end in **.py** if you are using a Python script.



# Google CoLab Instructions

The following code ensures that Google CoLab is running the correct version of TensorFlow.



In [20]:
try:
    from google.colab import drive
    %tensorflow_version 2.x
    COLAB = True
    print("Hello World")
    print("Note: using Google CoLab")
except:
    print("Hello NITD")
    print("Note: not using Google CoLab")
    COLAB = False

# Print your name and Roll No.
# Print the curent time

Hello NITD
Note: not using Google CoLab


**Exercise 1.** Create following list:

data = [2,34,23,16,56,45,34,26,78,56,1,16]

Write a function to count number of elements in a list . <br>
Now delete the duplicate values and print the list in ascending order.

In [19]:
num = input("enter the number")
numbers = list(map(int, num.split()))
count = len(numbers) 
unique = list(dict.fromkeys(numbers))
print ("the count is",count)
unique.sort()
print("Numbers without duplicates and ascending:", unique)


enter the number 2 3 12 4 12 4 2 4 8 6 9 89


the count is 12
Numbers without duplicates and ascending: [2, 3, 4, 6, 8, 9, 12, 89]


**Exercise 2:** Take five numbers as input from the user and save into a list. Find the maximum of the list and sort the data in descending order.

In [22]:
num = input("enter 5 number")
num = list(map(int, num.split()))
num.sort(reverse = True)
print("in decending order", num)
maximum = max(num)
print ("the maximum is",maximum)

enter 5 number 1 2 3 1 12 3 54


in decending order [54, 12, 3, 3, 2, 1, 1]
the maximum is 54


**Exercise 4:**

(i) Generate two arrays A1 and A2 of size 5 X 4 and 3 X 4 respectively using np.random()

(ii) Join them and make an array A3 of 8 X 4. Now append random numbers ranging between from 0 to 5 to make the fourth array A4 of size 10 X 10.

(iii) Print all the arrays and their transpose ( Transpose of 'A' can be obtained by 'A.T')

In [23]:
import numpy as np
A1 = np.random.rand(5,4)
A2 = np.random.rand(3,4)
A3 = np.vstack((A1,A2))
A4 = np.random.randint(0,6,(10,10))
A4[:8,:4] = A3
print("A1 = ")
print(A1)
print("A1 Transpose = ")
print(A1.T)
print("A2 = ")
print(A2)
print("A2 Transpose = ")
print(A2.T)
print("A3 = ")
print(A3)
print("A3 Transpose = ")
print(A3.T)
print("A4 = ")
print(A4)
print("A4 Transpose = ")
print(A4.T)

A1 = 
[[0.52199401 0.56649275 0.38005543 0.72592528]
 [0.26825268 0.10075512 0.97524174 0.95887108]
 [0.03933786 0.86698504 0.52427543 0.55400752]
 [0.73914059 0.67954781 0.8073539  0.11928369]
 [0.67624466 0.55270338 0.09109681 0.08194941]]
A1 Transpose = 
[[0.52199401 0.26825268 0.03933786 0.73914059 0.67624466]
 [0.56649275 0.10075512 0.86698504 0.67954781 0.55270338]
 [0.38005543 0.97524174 0.52427543 0.8073539  0.09109681]
 [0.72592528 0.95887108 0.55400752 0.11928369 0.08194941]]
A2 = 
[[0.93657245 0.91830341 0.26060734 0.86797398]
 [0.58646583 0.07429292 0.03848458 0.42708994]
 [0.20974192 0.96235136 0.05076028 0.52466933]]
A2 Transpose = 
[[0.93657245 0.58646583 0.20974192]
 [0.91830341 0.07429292 0.96235136]
 [0.26060734 0.03848458 0.05076028]
 [0.86797398 0.42708994 0.52466933]]
A3 = 
[[0.52199401 0.56649275 0.38005543 0.72592528]
 [0.26825268 0.10075512 0.97524174 0.95887108]
 [0.03933786 0.86698504 0.52427543 0.55400752]
 [0.73914059 0.67954781 0.8073539  0.11928369]
 [0.67

**Exercise 5: Create two dictionaries.**

The first dictionary 'name' will contain first name(key) of a person and its hash value(value).
The Second will contain hash value(key) and mobile no(value).


i) Add 5 entries.

ii) Delete two entries by taking the input from user as the first name.

ii) Add two entries by taking the input as the first name and mobile no.

Hint: You can use remainder ( %) to obtain hash value.

In [24]:
name={}
mobile={}
for i in range(5):
    n=input("Enter name: ")
    m=int(input("Enter mobile number: "))
    h=m%1000
    name[n]=h
    mobile[h]=m
print("Name dictionary:")
print(name)
print("Mobile dictionary:")
print(mobile)
for i in range(2):
    n=input("Enter name to delete: ")
    h=name[n]
    del name[n]
    del mobile[h]
print("After deleting:")
print(name)
print(mobile)
for i in range(2):
    n=input("Enter new name: ")
    m=int(input("Enter mobile number: "))
    h=m%1000
    name[n]=h
    mobile[h]=m
print("Final dictionaries:")
print(name)
print(mobile)

Enter name:  Aashish
Enter mobile number:  8603076065
Enter name:  Aashish 
Enter mobile number:  9851036009
Enter name:  arjun 
Enter mobile number:  9841212425
Enter name:  Indira
Enter mobile number:  9702775463
Enter name:  ambika
Enter mobile number:  9851036805


Name dictionary:
{'Aashish': 65, 'Aashish ': 9, 'arjun ': 425, 'Indira': 463, 'ambika': 805}
Mobile dictionary:
{65: 8603076065, 9: 9851036009, 425: 9841212425, 463: 9702775463, 805: 9851036805}


Enter name to delete:  Aashish
Enter name to delete:  ARJUN


KeyError: 'ARJUN'

# PART 2: Introduction to NumPy    


**Exercise 6:** Write a NumPy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays

In [25]:
def compare_arrays(arr1, arr2):
    if not isinstance(arr1, np.ndarray) or not isinstance(arr2, np.ndarray):
        raise TypeError("Both inputs must be NumPy arrays.")
    if arr1.shape != arr2.shape:
        raise ValueError("Arrays must have the same shape for element-wise comparison.")
    return {
        "greater": np.greater(arr1, arr2),
        "greater_equal": np.greater_equal(arr1, arr2),
        "less": np.less(arr1, arr2),
        "less_equal": np.less_equal(arr1, arr2)
    }
if __name__ == "__main__":
    array1 = np.array([3, 5, 7, 9])
    array2 = np.array([2, 5, 8, 9])
    try:
        results = compare_arrays(array1, array2)
        print("Array 1:", array1)
        print("Array 2:", array2)
        print("\nElement-wise Comparisons:")
        for key, value in results.items():
            print(f"{key}: {value}")
    except (TypeError, ValueError) as e:
        print("Error:", e)

Array 1: [3 5 7 9]
Array 2: [2 5 8 9]

Element-wise Comparisons:
greater: [ True False False False]
greater_equal: [ True  True False  True]
less: [False False  True False]
less_equal: [False  True  True  True]


**Exercise 7:** Write a NumPy program to create an array with the values 100, 71, 113, 1050 and determine the size of the memory occupied by the array.

In [28]:
arr = np.array([100,71,113,1050])
print ("array",arr)
memory_size = arr.nbytes
print("the memory size is",memory_size)

array [ 100   71  113 1050]
the memory size is 16


**Exercise 8:** Write a NumPy program to get the powers ( x ^ 3 ) of an array values element-wise


Expected Output:
Original array
[1 2 3 4 5 ]
Output array:
[ 1 8 27 64 125 ]

In [29]:
a=np.array(list(map(int,input().split())))
print(np.power(a,3))

 2 3 1 3 4 1 


[ 8 27  1 27 64  1]


**Exercise 9:** Write a NumPy program to get the floor, ceiling and truncated values of the elements of a numpy array.
Sample Output:
Original array:
[-1.3, -1.15, -0.1, 0.12, 1.7, 0.9, 1.1]

In [ ]:
np.array(list(map(float,input().split())))
print(np.floor(a))
print(np.ceil(a))
print(np.trunc(a))e here

**Exercise 10:** Write a program in python to display prime numbers from x to y (here x and y are user given values).

In [ ]:
x,y=map(int,input().split())
for n in range(x,y+1):
    if n>1:
        for i in range(2,int(n**0.5)+1):
            if n%i==0:
                break
        else:
            print(n,end=' ')

## Hint :

Reference Book to learn python: https://anandology.com/python-practice-book/getting-started.html